export const AGREEMENTS_COLLECTION_NAME = 'agreements'
export const ATTRIBUTES_COLLECTION_NAME = 'attributes'
export const CLIENTS_COLLECTION_NAME = 'clients'
export const ESERVICES_COLLECTION_NAME = 'eservices'
export const KEYS_COLLECTION_NAME = 'keys'
export const PURPOSES_COLLECTION_NAME = 'purposes'
export const TENANTS_COLLECTION_NAME = 'tenants'