export const MACRO_CATEGORIES = [
  {
    id: '1',
    name: 'Altre Pubbliche Amministrazioni locali',
    ipaCodes: [
      'C13',
      'C7',
      'C3',
      'C14',
      'L10',
      'L19',
      'L13',
      'L2',
      'L20',
      'L21',
      'L1',
      'L40',
      'L11',
      'L39',
      'L46',
      'L34',
      'L35',
      'L47',
      'L12',
      'L24',
      'L42',
      'L36',
      'L44',
      'L16',
      'L38',
      'L31',
    ],
  },
  {
    id: '2',
    name: 'Aziende Ospedaliere e ASL',
    ipaCodes: ['L8', 'L22', 'L7'],
  },
  {
    id: '3',
    name: 'Comuni',
    ipaCodes: ['L18', 'L6'],
  },
  {
    id: '4',
    name: 'Province e Città Metropolitane',
    ipaCodes: ['L5', 'L45'],
  },
  {
    id: '5',
    name: 'Pubbliche Amministrazioni Centrali',
    ipaCodes: ['C10', 'C5', 'C11', 'C1', 'C2'],
  },
  {
    id: '6',
    name: 'Enti Nazionali di Previdenza ed Assistenza Sociale',
    ipaCodes: ['C16', 'C17'],
  },
  {
    id: '7',
    name: 'Regioni',
    ipaCodes: ['L4999'],
  },
  {
    id: '8',
    name: 'Consorzi e associazioni regionali',
    ipaCodes: ['L4'],
  },
  {
    id: '9',
    name: 'Scuole',
    ipaCodes: ['L33'],
  },
  {
    id: '10',
    name: 'Università e AFAM',
    ipaCodes: ['L17', 'L15', 'L43'],
  },
  {
    id: '11',
    name: 'Istituti di Ricerca',
    ipaCodes: ['C8', 'C12', 'L28'],
  },
  {
    id: '12',
    name: 'Stazioni Appaltanti e Gestori di pubblici servizi',
    ipaCodes: ['SAG', 'L37', 'S01', 'SA'],
  },
] as const
