name: Continuous Integration

on:
  push:
    branches: ['**']
    tags: ['**']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Installing
        run: pnpm install

      - name: Building
        run: pnpm build

      - name: Testing
        run: pnpm test

  single-job:
    name: Continuos Integration
    strategy:
      matrix:
        jobs: [dtd-catalog-exporter, one-trust-notices, registered-comuni-pn]
        node: [18.15.0]
    uses: ./.github/workflows/single-job.yml
    secrets: inherit
    with:
      job-name: ${{ matrix.jobs }}
      node-version: ${{ matrix.node }}
